development:
  adapter: postgresql
  host: localhost
  username: mollyyang
  database: heartapp_development

test:
  adapter: postgresql
  encoding: unicode
  database: heartapp_test
  pool: 5
  username: ukarrfycgjwwqj
  password: 3_ojAge4DHt5Ve8pAW9hOKgthe

production:
  adapter: postgresql
  encoding: unicode
  database: heartapp_production
  pool: 5
  username: ukarrfycgjwwqj
  password: 3_ojAge4DHt5Ve8pAW9hOKgthe