development:
  adapter: postgresql
  encoding: unicode
  database: heartapp_development
  pool: 5
  username: mollyyang
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: heartapp_test
  pool: 5
  username: mollyyang
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: heartapp_production
  pool: 5
  username: mollyyang